### ISSUE TITLE
Upgrade the dependency to Kairos to 1.2.0

### ISSUE THREAD

**Issue by martin-g** [kairosdb/kairosdb-client#69]
At the moment the client depends on Kairos 1.1.3.
Would it be OK to upgrade it to 1.2.0 ?

**Comment by martin-g** [comment]
I am not sure whether it is related or not but I've got some of those in production:
```
ERROR 05/04 18:04:55.003 - com.cryptoapi.metrics.KairosdbClient - Cannot send to KairosDB
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:768)
	at org.kairosdb.client.JsonMapper.fromJson(JsonMapper.java:27)
	at org.kairosdb.client.AbstractClient.getResponse(AbstractClient.java:131)
	at org.kairosdb.client.AbstractClient.pushMetrics(AbstractClient.java:89)
    ...
```

I.e. Kairos client sends the request but fails while parsing the response, actually when checking for errors.

I cannot reproduce it locally though.
Kairos client: 2.2.0
Kairos Server: 1.2.1
